# Generated by Django 4.2.30 on 2026-09-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
    ]
