# Generated by Django 4.2.30 on 2026-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20260916_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
