# Generated by Django 4.2.16 on 2026-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experience_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
