# Generated by Django 4.2.16 on 2026-09-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_logo_url_alter_education_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
